---
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--color --format documentation'\""
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
Gemfile:
  required:
    ':test':
      - gem: rake
      - gem: rspec-puppet
      - gem: puppet-lint
      - gem: metadata-json-lint
      - gem: rspec-puppet-facts
      - gem: rspec
      - gem: rspec-puppet-utils
      - gem: puppetlabs_spec_helper
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
Guardfile:

  guard 'rake', :task => 'validate' do
    watch(%r{^hiera\/.+\.yaml$})
    watch(%r{^manifests\/.+\.pp$})
    watch(%r{^metadata.json$})
    watch(%r{^templates\/.+\.erb$})
    watch(%r{^tests\/.+\.pp$})
  end

  guard 'rake', :task => 'lint' do
    watch(%r{^manifests\/.+\.pp$})
  end

  guard 'rake', :task => 'spec' do
    watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
    watch(%r{^manifests\/.+\.pp$})
    watch(%r{^templates\/.+\.erb$})
    watch(%r{^spec/.+_spec\.rb$})
    watch('spec/spec_helper.rb')  { "spec" }
  end
