---
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--color --format documentation'\""
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
Gemfile:
  required:
    ':test':
      - gem: rspec-core
      - gem: puppetlabs_spec_helper
      - gem: simplecov
      - gem: puppet_facts
      - gem: metadata-json-lint
    ':development':
      - gem: travis
      - gem: travis-lint
      - gem: guard-rake
      - gem: puppet-strings
        git: https://github.com/puppetlabs/puppetlabs-strings.git
      - gem: redcarpet
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker-puppet_install_helper
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
