---
.travis.yml:
  script: "\"bundle exec rake validate lint rubocop spec SPEC_OPTS='--color --format documentation'\""
  includes:
    - rvm: 2.2.7
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.3.4
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
    - rvm: 2.3.4
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
    - rvm: 2.4.1
      env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES="yes"
Gemfile:
  required:
    ':test':
      - gem: json
        version: < 2.0.0
        ruby-operator: '<'
        ruby-version: '2.0.0'
      - gem: json_pure
        version: <= 2.0.1
        ruby-operator: '<'
        ruby-version: '2.0.0'
      - gem: metadata-json-lint
      - gem: puppet-strings
      - gem: puppet_facts
      - gem: puppetlabs_spec_helper
      - gem: rspec-core
      - gem: rspec-puppet-facts
      - gem: rubocop
        version: '~> 0.49.0'
      - gem: rubocop-rspec
        version: '~> 1.10.0'
      - gem: simplecov
    ':development':
      - gem: github_changelog_generator
        version: '~> 1.13.0'
        ruby-operator: '<'
        ruby-version: '2.2.2'
      - gem: rack
        version: '~> 1.0'
        ruby-operator: '<'
        ruby-version: '2.2.2'
      - gem: github_changelog_generator
        ruby-operator: '>='
        ruby-version: '2.2.2'
      - gem: guard-rake
      - gem: parallel_tests
      - gem: puppet-blacksmith
      - gem: redcarpet
      - gem: travis
      - gem: travis-lint
    ':integration':
      - gem: concurrent-ruby
        version: '~> 0.9'
      - gem: kitchen-inspec
      - gem: kitchen-puppet
      - gem: kitchen-vagrant
      - gem: librarian-puppet
      - gem: test-kitchen
        version: '~> 1.4'
Rakefile:
  default_disabled_lint_checks:
    - 'relative'
    - 'disable_140chars'
    - 'disable_class_inherits_from_params_class'
    - 'disable_documentation'
    - 'disable_single_quote_string_with_variables'
