---
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--color --format documentation'\""
  includes:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
Gemfile:
  required:
    ':test':
      - gem: json
        version: 1.8.3
      - gem: json_pure
        version: 2.0.1
      - gem: metadata-json-lint
      - gem: puppet-strings
      - gem: puppet_facts
      - gem: puppetlabs_spec_helper
      - gem: rspec-core
      - gem: rspec-puppet-facts
      - gem: simplecov
    ':development':
      - gem: guard-rake
      - gem: redcarpet
      - gem: travis
      - gem: travis-lint
    ':integration':
      - gem: concurrent-ruby
        version: '~> 0.9'
      - gem: kitchen-inspec
      - gem: kitchen-puppet
      - gem: kitchen-vagrant
      - gem: librarian-puppet
      - gem: test-kitchen
        version: '~> 1.4'
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
