require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
if File.exist?('puppet-strings/rake_tasks')
    require 'puppet-strings/rake_tasks'
end

PuppetLint.configuration.fail_on_warnings = true
<% checks = @configs['default_disabled_lint_checks'] + ( @configs['extra_disabled_lint_checks'] || [] ) -%>
<% checks.each do |check| -%>
PuppetLint.configuration.send('<%= check %>')
<% end -%>
PuppetLint.configuration.ignore_paths = ["spec/**/*.pp", "pkg/**/*.pp"]
